# Site settings
name: Joshua Yi
location: Santa Clara
company: Santa Clara University
position: Student
github: https://github.com/j-r-yi
facebook: https://www.facebook.com/joshua.yi.5015
phone: +1 6692981618
email: joshuayi2004@gmail.com

baseurl: '/personal-website'
# baseurl: '/resume.io'
# domain: Joshua-R-Yi.github.io
# url: https://Joshua-R-Yi.github.io
# baseurl: 'resume_joshua'

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown
